export const SERVICES = [
  {
    name: "General Contracting",
    desc: "We handle everything for you — from framing and drywall to painting, tiling, flooring, and hardware installation. No need to coordinate multiple contractors, we manage it all.",
    icon: "FaHammer",
    link: "/services/general-contracting",
  },
  {
    name: "Project Management & Consulting",
    desc: "We specialize in creating restaurants, retail, and office environments that are functional, beautiful, and built to last. Your partner from start to finish.",
    icon: "FaProjectDiagram",
    link: "/services/project-management-consulting",
  },
  {
    name: "Commercial Accessible Construction",
    desc: "We design and build commercial spaces accessible to everyone. Every detail meets accessibility standards while looking great and functioning smoothly.",
    icon: "FaWheelchair",
    link: "/services/commercial-accessible-construction",
  },
  {
    name: "Commercial Reno",
    desc: "We transform existing commercial spaces into modern, functional, and accessible environments. We handle every step from planning to finishing.",
    icon: "FaBuilding",
    link: "/services/commercial-reno",
  },
  {
    name: "Electrical Services",
    desc: "We take care of all your electrical needs — from wiring and lighting to installations and maintenance. Our skilled team ensures everything works flawlessly.",
    icon: "FaBolt",
    link: "/services/electrical-services",
  },
  {
    name: "Plumbing Services",
    desc: "We handle all your plumbing installations and maintenance needs. Our skilled team ensures your space works flawlessly and meets the highest standards.",
    icon: "FaWrench",
    link: "/services/plumbing-services",
  },
  {
    name: "Millwright & Custom Fabrication",
    desc: "We provide expert millwright and custom fabrication services for specialized commercial projects. Precision installations and custom-built components that fit perfectly.",
    icon: "FaCog",
    link: "/services/millwright-custom-fabrication",
  },
  {
    name: "Walk-In Coolers & Freezers",
    desc: "We design and install walk-in coolers and freezers that keep your business running smoothly. From planning to maintenance, we handle every step.",
    icon: "FaSnowflake",
    link: "/services/walk-in-coolers-freezers",
  },
  {
    name: "Maintenance & Emergency Services",
    desc: "We keep your commercial space running smoothly every day and in emergencies. From regular maintenance to urgent repairs, we respond quickly.",
    icon: "FaPhone",
    link: "/services/maintenance-emergency-services",
  },
  {
    name: "Hood Installation",
    desc: "Provide you with the best arrangement and alignment service along with safety. We specialize in the installation, maintenance, and arrangement of Hood.",
    icon: "FaFan",
    link: "/services/hood-installation",
  },
  {
    name: "Architecture Drawing",
    desc: "We provide you with Architectural Drawings that are the foundation for the construction and remodeling project.",
    icon: "FaDraftingCompass",
    link: "/services/architecture-drawing",
  },
  {
    name: "Retail Remodeling",
    desc: "Modernize your space with unlimited creativity in design and specialized installation.",
    icon: "FaStore",
    link: "/services/retail-remodeling",
  },
  {
    name: "Home Renovation",
    desc: "Revamping your homely space with architectural beauty and recollections.As your likes blend the tastes with modern and traditional works. Remould your home space professionally, and get customized home design and decor.",
    icon: "FaHome",
    link: "/services/home-renovation",
  },
  {
    name: "Supplies",
    desc: "Providing the parties with complete equipment and services. Make available the tools and supplies you need.",
    icon: "FaBox",
    link: "/services/supplies",
  },
  {
    name: "Your Request?",
    desc: "We're here to deliver you with the best solutions for your space. Let's put together your space more attractive.",
    icon: "FaQuestionCircle",
    link: "/services/your-request",
  },
];
